# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kerwin Chen Testing
email: kerwinyanchen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Jekyll demo site testing, kerwin
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: kerwinyanchen
github_username:  kerwinyanchen

webrick:
  headers:
    My-Header: My-kkk
    My-Other-Header: My-Other-Value

# Build settings
name: Kerwin Chen, Testing
markdown: kramdown
theme: minima

permalink: /blog/:year/:month/:day/:title
